import type { InventoryItem } from './types'

export const inventory: InventoryItem[] = [
  {
    id: 'lantern-gold',
    name: 'Gold Lantern — Large',
    category: 'Centerpieces',
    color: 'Gold',
    quantity: 18,
    dimensions: '14 in tall × 6 in wide',
    storage: 'Shed · Shelf B3',
    description: 'Warm brushed-gold lantern with glass panels. Works well with greenery rings or pillar candles.',
    imageStyle: 'gold-lantern',
    featured: true,
  },
  {
    id: 'vase-white',
    name: 'White Ceramic Bud Vase',
    category: 'Vases',
    color: 'Ivory',
    quantity: 30,
    dimensions: '6 in tall',
    storage: 'Shed · Shelf C1',
    description: 'Matte ivory bud vase for small floral clusters and mixed tabletop arrangements.',
    imageStyle: 'white-vase',
    featured: true,
  },
  {
    id: 'candle-brass',
    name: 'Brass Taper Candle Holder',
    category: 'Candles',
    color: 'Antique brass',
    quantity: 48,
    dimensions: 'Assorted 7–11 in',
    storage: 'Shed · Bin C4',
    description: 'Assorted-height brass candle holders for layered centerpieces.',
    imageStyle: 'brass-candle',
  },
  {
    id: 'welcome-wood',
    name: 'Wooden Welcome Sign',
    category: 'Signs',
    color: 'Natural wood',
    quantity: 2,
    dimensions: '24 × 36 in',
    storage: 'Shed · Back wall',
    description: 'Freestanding natural wood welcome sign with interchangeable acrylic lettering panel.',
    imageStyle: 'wood-sign',
    featured: true,
  },
  {
    id: 'arch-wood',
    name: 'Natural Wood Ceremony Arch',
    category: 'Arches',
    color: 'Natural wood',
    quantity: 1,
    dimensions: '7 ft × 7 ft',
    storage: 'Shed · Wall rack A',
    description: 'Simple square ceremony arch suitable for florals, draping, greenery, or lights.',
    imageStyle: 'wood-arch',
  },
  {
    id: 'runner-sage',
    name: 'Sage Gauze Table Runner',
    category: 'Linens',
    color: 'Sage',
    quantity: 22,
    dimensions: '10 ft long',
    storage: 'Linen room · Bin L2',
    description: 'Soft gauze runner with a relaxed drape for round or banquet tables.',
    imageStyle: 'sage-runner',
  },
  {
    id: 'greenery-ring',
    name: 'Eucalyptus Greenery Ring',
    category: 'Florals',
    color: 'Green',
    quantity: 24,
    dimensions: '18 in diameter',
    storage: 'Shed · Floral bin F2',
    description: 'Reusable eucalyptus greenery ring sized for lantern and vase centerpieces.',
    imageStyle: 'greenery-ring',
  },
  {
    id: 'aisle-lantern',
    name: 'Black Aisle Lantern',
    category: 'Ceremony',
    color: 'Black',
    quantity: 12,
    dimensions: '12 in tall',
    storage: 'Shed · Shelf B1',
    description: 'Matte black aisle lantern with removable LED candle insert.',
    imageStyle: 'black-lantern',
  },
  {
    id: 'table-number',
    name: 'Gold Acrylic Table Number',
    category: 'Signs',
    color: 'Gold',
    quantity: 25,
    dimensions: '5 × 7 in',
    storage: 'Office · Drawer 3',
    description: 'Modern gold acrylic table numbers with clear stands, numbered 1–25.',
    imageStyle: 'table-number',
  },
  {
    id: 'cylinder-vase',
    name: 'Clear Glass Cylinder Vase',
    category: 'Vases',
    color: 'Clear',
    quantity: 36,
    dimensions: 'Assorted 6–10 in',
    storage: 'Shed · Shelf C2',
    description: 'Simple glass cylinders for candles, florals, floating candles, or layered centerpieces.',
    imageStyle: 'glass-vase',
  },
  {
    id: 'drape-white',
    name: 'Ivory Ceremony Draping',
    category: 'Ceremony',
    color: 'Ivory',
    quantity: 4,
    dimensions: '20 ft panels',
    storage: 'Linen room · Hanging rack',
    description: 'Lightweight ivory chiffon panels for arches, ceremony backdrops, or sweetheart tables.',
    imageStyle: 'ivory-drape',
  },
  {
    id: 'card-box',
    name: 'Glass & Brass Card Box',
    category: 'Miscellaneous',
    color: 'Brass / clear',
    quantity: 2,
    dimensions: '12 × 8 × 8 in',
    storage: 'Office · Cabinet 2',
    description: 'Glass card box with brass frame and hinged top for gift or welcome tables.',
    imageStyle: 'card-box',
  },
]

export const sampleWeddings = [
  { couple: 'Sarah & John', date: '2026-10-17', status: 'Ready', guests: 125, selections: 42 },
  { couple: 'Ashley & Mark', date: '2026-10-24', status: 'Designing', guests: 90, selections: 18 },
  { couple: 'Jennifer & Matt', date: '2026-11-07', status: 'Not started', guests: 150, selections: 0 },
]
